### ISSUE TITLE
suggestion: can offset support the second parameter

### ISSUE THREAD

**Issue by bplok20010** [react-bootstrap/dom-helpers#105]
I don't want to create a package to implement the set offset function. Can dom-helpers support it?
e.g.
```
offset(node, {
top: 100
})

offset(node, {
top: 100,
left: 100
})
```

**Comment by taion** [comment]
How would it do this?

**Comment by bplok20010** [comment]
@taion 
offset can only obtain the location information of a node at present, but I also hope to set its location information, such as when dragging.

> jQuery has such functions, sometimes it is very convenient.

**Comment by jquense** [comment]
You can use the `css()` method to do that. That's what jquery is doing and it's probably not worth the extra code path here.

**Comment by bplok20010** [comment]
@jquense 
The  `css()` method  can do it.
What I hope is that users don't need to pay attention to the level of DOM, and use offset(e.g `offset(node,coords )`) to set the coordinates relative to the window, which actually extends the function of offset, but it does bring more code.
But they look like a couple :).

**Comment by bplok20010** [comment]
I created a npm package to implement.

repo: https://github.com/bplok20010/dom-helpers-extra
