### ISSUE TITLE
SVG element doesn't have _contains_ on IE

### ISSUE THREAD

**Issue by wvengen** [react-bootstrap/dom-helpers#11]
On IE9 and IE11 I'm seeing the error message _Object doesn't support property or method 'contains'_. This is shown in the IE11 error console:

![ie11](https://cloud.githubusercontent.com/assets/503804/19353008/4771c67c-9162-11e6-9527-81d7abf2155b.png)

Would it be that there is a problem with SVG elements on IE?

Also:
```
> $('p')[0]
<p class="...">...</p>
> $('p')[0].contains
function contains() { [native code] }
> $('circle')[0]
[object Object]
> $('circle')[0].contains
undefined
```

**Comment by wvengen** [comment]
https://bugs.jquery.com/ticket/10832 is a similar issue on jQuery

**Comment by jquense** [comment]
oops, PR?
