### ISSUE TITLE
Incorrect transitionEnd event name reported in Firefox

### ISSUE THREAD

**Issue by hannesj** [react-bootstrap/dom-helpers#17]
dom-helpers currently report `mozTransitionEnd` as the event name for  Firefox, which is not implemented anymore in Firefox. Instead the standard `transitionend` should be used.

**Comment by hannesj** [comment]
This seems to be a regression from d5af3ef2ef2ba83b971748a059219de176691513

**Comment by oliviertassinari** [comment]
I was able to reproduce the issue. I confirm.

**Comment by jquense** [comment]
fixed in 3.2.1, thanks @oliviertassinari and @hannesj

**Comment by hannesj** [comment]
Thanks!

la 4. helmikuuta 2017 klo 9.16 Jason Quense <notifications@github.com>
kirjoitti:
