### ISSUE TITLE
scrollbarSize always returns 0

### ISSUE THREAD

**Issue by griffinmichl** [react-bootstrap/dom-helpers#28]
I've been noticing that scrollbarSize only ever returns zero. I feel like in the past I used this function to successfully measure scrollbars, but it seems to not work properly anymore. Maybe a browser update? I'm not really sure what's going on.

Test in Chrome 60.0.3112.90

**Comment by jquense** [comment]
are on a mac with floating scrollbars?

**Comment by griffinmichl** [comment]
I am on OSX El Capitan (10.11.6).  

Is there no way to measure the width of the scrollbars on this OS?

**Comment by jquense** [comment]
The width of a scrollbar is determined by how much of the window it takes up. If you have the floating scrollbars turned on they don't take up any space because they disappear and overlay the content when visible

**Comment by griffinmichl** [comment]
Fair enough. Thanks!
