### ISSUE TITLE
DOMException: Failed to execute 'add' on 'DOMTokenList': 

### ISSUE THREAD

**Issue by bradennapier** [react-bootstrap/dom-helpers#30]
Getting this error - not really sure where this module is used in my project atm but its this module causing the error in my system.

The token provided ('[object Object]-appear') contains HTML space characters, which are not valid in tokens.

-appear makes me think it is the react addon for css transition...

**Comment by jquense** [comment]
The problem is you are passing an object instead of a string somewhere, The issue isn't here tho, the error you'r getting is correct, you'll need to fix it further up the stack
