### ISSUE TITLE
Transition properties returning the incorrect end animation for Chrome latest (v61)

### ISSUE THREAD

**Issue by jeffchan** [react-bootstrap/dom-helpers#31]
![image](https://user-images.githubusercontent.com/97428/30079860-81a19cf2-9236-11e7-80b7-528b3d3a8b24.png)

Expected: `animationEnd` and `transitionEnd` (according to https://developer.mozilla.org/en-US/docs/Web/Events/transitionend)

Actual: `webkitAnimationEnd` and `webkitTransitionEnd`

I believe this is because https://github.com/react-bootstrap/dom-helpers/blob/fd4a81c0ac207c548d4f25d19e0a8c59fc41ee5d/src/transition/properties.js#L68 Chrome has both `style.transitionProperty` and `style.webKitTransitionProperty`

In contrast, React v15's detection is more robust and returns the correct property:
https://github.com/facebook/react/blob/master/src/renderers/shared/shared/event/getVendorPrefixedEventName.js

**Comment by taion** [comment]
no longer relevant in the current version
