### ISSUE TITLE
Question: Does this exist on a cdn?

### ISSUE THREAD

**Issue by skiano** [react-bootstrap/dom-helpers#34]
I was hoping to use this package through https://unpkg.com/dom-helpers@3.2.1/index.js or perhaps https://cdnjs.com/.

Is this something that makes sense?

Thanks!

**Comment by jquense** [comment]
it's doesn't exist in a non-module bundled form. The main value of the library is the ability to pick and choose the utils you need from the package, bundling it together would defeat that purpose.

**Comment by skiano** [comment]
Thanks for the reply! That totally makes sense. I was just thinking it may be convenient to have the whole thing :), especially to start with.
