### ISSUE TITLE
`scrollbarSize` util function not documented in README

### ISSUE THREAD

**Issue by reyronald** [react-bootstrap/dom-helpers#39]
The utility function `scrollbarSize` is not documented in the README, yet it is as usable as the rest of the exposed functions. Is there a reason behind this? 

I haven't checked thoroughly, but there _might_ be other functions that could be exposed as well that aren't documented either.

**Comment by jquense** [comment]
Care to send a PR?

**Comment by reyronald** [comment]
Definitely! Just wanted to make sure there wasn't a reason I was not aware of!
