### ISSUE TITLE
Overlay problem in IE8: getBoundingClientRect does not support width and height

### ISSUE THREAD

**Issue by w-y** [react-bootstrap/dom-helpers#4]
https://github.com/react-bootstrap/dom-helpers/blob/master/src/query/offset.js#L21

```
if (node.getBoundingClientRect !== undefined)
    box = node.getBoundingClientRect();
    if ( box.width || box.height ) {
        box = {
            top:    box.top  + (win.pageYOffset || docElem.scrollTop)  - (docElem.clientTop  || 0),
            left:   box.left + (win.pageXOffset || docElem.scrollLeft) - (docElem.clientLeft || 0),
            width:  (box.width  == null ? node.offsetWidth  : box.width)  || 0,
            height: (box.height == null ? node.offsetHeight : box.height) || 0
       }
   }
```

"box.width || box.height"  will always be false in IE8 then the calculated offset may become NaN.

**Comment by jquense** [comment]
Thanks for the report, to be honest I have no idea what the check is there for it seems to be a weird addition, Feel like sending a PR to fix it?

**Comment by w-y** [comment]
PR: https://github.com/react-bootstrap/dom-helpers/pull/5

just remove "if ( box.width || box.height )".
if getBoundingClientRect return undefined width and height then it will be set.
I have tested in IE 8 and the box's values is correct.

**Comment by xcatliu** [comment]
+1
