### ISSUE TITLE
Release process?

### ISSUE THREAD

**Issue by rhenwood-arm** [react-bootstrap/dom-helpers#52]
Hi @taion;

It would be helpful for me to have a 'release' made that includes the commits since the last release. Do you plan to make a release?

best regards,
Richard

**Comment by taion** [comment]
@jquense can you cut a new release?

**Comment by jquense** [comment]
Not today, but ping me tomorrow and yeah.

**Comment by rhenwood-arm** [comment]
Hi @jquense 
A little later than requested, but: ping :)

**Comment by jquense** [comment]
done!
