### ISSUE TITLE
@babel/runtime in dependencies

### ISSUE THREAD

**Issue by gwilson2151** [react-bootstrap/dom-helpers#54]
Is it intentional in package.json that @babel/runtime is in dependencies as opposed to devDependnencies?

**Comment by TrySound** [comment]
@gwilson2151 Yes. Babel runtime is a collection of reusable helpers. It allows to prevent inlining of these helpers in each file. This package can be even reused across many packages so you don't loose anything with it.
https://unpkg.com/dom-helpers@3.4.0/class/addClass.js

**Comment by gwilson2151** [comment]
OK, just confused that a babel package showed up in our lock file when we don't use babel.
