### ISSUE TITLE
Add option for passive event listeners

### ISSUE THREAD

**Issue by nosovk** [react-bootstrap/dom-helpers#62]
According an article https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners
we currently could use passive listeners for scroll events
here is an example how to detect their avalibility https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

Currently there is no way to specify that our listener is passive.

**Comment by taion** [comment]
`addEventListener` actually supports the `passive` option and appropriately sniffs for its availability: https://github.com/react-bootstrap/dom-helpers/blob/v5.1.0/src/addEventListener.ts
