### ISSUE TITLE
transitionEnd doesn't pass handler through to emulateTransitionEnd

### ISSUE THREAD

**Issue by JoshuaWarejko** [react-bootstrap/dom-helpers#70]
## Describe the bug

`transitionEnd` does not run handler for browsers that do not pass `TRANSITION_END` support check.

## To Reproduce

1. Use transition end in a browser that does not pass `'ontransitionend' in window` or `canUseDOM` check.

## Expected behavior

The handler should still be ran for browsers that do not pass the above check.

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version: IE 11
- React-Bootstrap Version: 1.0.0-beta.11

## Additional context

`TRANSITION_SUPPORTED` variable is always false for IE 11.

**Comment by mxschmitt** [comment]
Original issue: react-bootstrap/react-bootstrap/issues/4933

I'm not directly into context, but we should probably do something like described here to detect if TransitionEnd is supported in the browser: https://css-tricks.com/forums/topic/anyone-running-an-older-browser/#post-248375

**Comment by JoshuaWarejko** [comment]
I may be missing something, but I don't think think the issue is with TransitionEnd being supported in the browser. The issue is when TransitionEnd is not supported, it takes a different path and does't run the `handler` function. Just need the handler function to run, whether`TRANSITION_SUPPORTED` returns true or false.

**Comment by JoshuaWarejko** [comment]
For reference, I removed this block of code
```
if (!TRANSITION_SUPPORTED) {
    return emulateTransitionEnd(element, 0, 0);
 }
```
from inside the transitionEnd function and it ran properly in IE 11.

**Comment by jquense** [comment]
yes there is bug there, the listener should still be attached, there should an `else` on that if, not an early return

**Comment by haydenmorris88** [comment]
Is this going to be resolved anytime soon?

**Comment by jquense** [comment]
best way to get something resolved in a timeframe you prefer is to send a PR!
