### ISSUE TITLE
I am getting some issues with dom-helpers this morning, It was working fine on last week.

### ISSUE THREAD

**Issue by theshashiverma** [react-bootstrap/dom-helpers#75]
![image](https://user-images.githubusercontent.com/43005725/72701549-ac879300-3b75-11ea-90eb-5b5ad9677086.png)

**Comment by theshashiverma** [comment]
By downgrading the  react-swipeable-views to 0.13.1 solved my issue.

**Comment by daviseams** [comment]
thanks downgrading also helped me on my side
