### ISSUE TITLE
"cancelRequestAnimationFrame" API method check is missing

### ISSUE THREAD

**Issue by ikhilko** [react-bootstrap/dom-helpers#9]
When vendor prefixed `requestAnimationFrame` API method is established, corresponding `cancelRequestAnimationFrame` API method is assumed to be present. But some devices such as Samsung Galaxy S3 simply don't provide it.
The proposal is to check for the `cancelRequestAnimationFrame` as well.

**Comment by garthenweb** [comment]
Was looking for the same issue, nice to see this already fixed.
Will there be a patched version on npm soon?

**Comment by ikhilko** [comment]
Any progress on publishing this fix to npm?

**Comment by jquense** [comment]
there have been a few releases since this fixed was merged
